version: "3.8"

services:
  app-data-structure-php:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app-data-structure-php
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - xdebug-data:/tmp/xdebug
    environment:
      XDEBUG_MODE: coverage
      XDEBUG_CONFIG: remote_connect_back=1 remote_port=9003 remote_enable=1 profiler_enable=0 profiler_enable_trigger=1 profiler_output_dir=/tmp/xdebug mode=debug
      APPLICATION_ENV: development
    networks:
      - network-data-structure-php
    user: "1000:1000"

  nginx:
    image: nginx:latest
    container_name: nginx-data-structure-php
    ports:
      - "8888:80"
    volumes:
      - ./:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - network-data-structure-php


networks:
  network-data-structure-php:
    driver: bridge

volumes:
  xdebug-data:
    name: xdebug-data
