version: "3.8"

services:
  app-data-structure-php:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app-data-structure-php
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - xdebug-data:/tmp/xdebug
    environment:
      DB_HOST: db
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: root
      XDEBUG_MODE: coverage
      XDEBUG_CONFIG: remote_connect_back=1 remote_port=9003 remote_enable=1 profiler_enable=0 profiler_enable_trigger=1 profiler_output_dir=/tmp/xdebug mode=debug
      APPLICATION_ENV: development
    networks:
      - network-data-structure-php
    user: "1000:1000"

  nginx:
    build: .docker/nginx
    container_name: nginx-data-structure-php
    restart: always
    tty: true
    ports:
      - "8888:80"
    volumes:
      - ./:/var/www
    networks:
      - network-data-structure-php
    depends_on:
      - app-data-structure-php

#  db:
#    image: mysql:5.7
#    command: --innodb-use-native-aio=0
#    container_name: db
#    restart: always
#    tty: true
#    ports:
#      - "33006:3306"
#    volumes:
#      - ./.docker/dbdata:/var/lib/mysql
#    environment:
#      - MYSQL_DATABASE=laravel
#      - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_USER=root
#    networks:
#      - network-data-structure-php

networks:
  network-data-structure-php:
    driver: bridge

volumes:
  xdebug-data:
    name: xdebug-data
